package com.everis.equipo2semana4.pedidos.model;
// Generated 3/10/2019 10:21:35 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "examen3")
public class Pedido implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private Date fechahoraregistro;
	private Date fechahoraentrega;
	private Double precio;
	private Double descuento;
	private Double total;
	private Set<Producto> productos = new HashSet<Producto>(0);

	public Pedido() {
	}

	public Pedido(Cliente cliente) {
		this.cliente = cliente;
	}

	public Pedido(Cliente cliente, Date fechahoraregistro, Date fechahoraentrega, Double precio, Double descuento,
			Double total, Set<Producto> productos) {
		this.cliente = cliente;
		this.fechahoraregistro = fechahoraregistro;
		this.fechahoraentrega = fechahoraentrega;
		this.precio = precio;
		this.descuento = descuento;
		this.total = total;
		this.productos = productos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_idcliente", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechahoraregistro", length = 19)
	public Date getFechahoraregistro() {
		return this.fechahoraregistro;
	}

	public void setFechahoraregistro(Date fechahoraregistro) {
		this.fechahoraregistro = fechahoraregistro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechahoraentrega", length = 19)
	public Date getFechahoraentrega() {
		return this.fechahoraentrega;
	}

	public void setFechahoraentrega(Date fechahoraentrega) {
		this.fechahoraentrega = fechahoraentrega;
	}

	@Column(name = "precio", precision = 22, scale = 0)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	@Column(name = "descuento", precision = 22, scale = 0)
	public Double getDescuento() {
		return this.descuento;
	}

	public void setDescuento(Double descuento) {
		this.descuento = descuento;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "pedido_has_producto", catalog = "examen3", joinColumns = {
			@JoinColumn(name = "pedido_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "producto_id", nullable = false, updatable = false) })
	public Set<Producto> getProductos() {
		return this.productos;
	}

	public void setProductos(Set<Producto> productos) {
		this.productos = productos;
	}

}
