package com.everis.equipo2semana4.pedidos.model;
// Generated 3/10/2019 10:21:35 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name = "producto", catalog = "examen3")
public class Producto implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Double precio;
	private String url;
	private String descripcion;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Producto() {
	}

	public Producto(String nombre, Double precio, String url, String descripcion, Set<Pedido> pedidos) {
		this.nombre = nombre;
		this.precio = precio;
		this.url = url;
		this.descripcion = descripcion;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "precio", precision = 22, scale = 0)
	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "descripcion")
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "pedido_has_producto", catalog = "examen3", joinColumns = {
			@JoinColumn(name = "producto_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "pedido_id", nullable = false, updatable = false) })
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
