package com.everis.equipo2semana4.inventario.model;
// Generated 3/10/2019 12:09:30 PM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import static javax.persistence.GenerationType.IDENTITY;

/**
 * Inventario generated by hbm2java
 */
@Entity
@Table(name = "inventario", catalog = "semana4")
public class Inventario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idinventario;
	private Producto producto;
	private Integer movimiento;
	private Date fecha;

	public Inventario() {
	}

	public Inventario(int idinventario, Producto producto) {
		this.idinventario = idinventario;
		this.producto = producto;
	}

	public Inventario(int idinventario, Producto producto, Integer movimiento, Date fecha) {
		this.idinventario = idinventario;
		this.producto = producto;
		this.movimiento = movimiento;
		this.fecha = fecha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idinventario", unique = true, nullable = false)
	public int getIdinventario() {
		return this.idinventario;
	}

	public void setIdinventario(int idinventario) {
		this.idinventario = idinventario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "producto_idproducto", nullable = false)
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "movimiento")
	public Integer getMovimiento() {
		return this.movimiento;
	}

	public void setMovimiento(Integer movimiento) {
		this.movimiento = movimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fecha", length = 19)
	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}
